//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FindADocService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ThrCon8491123Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ThrCon8491123Entities object using the connection string found in the 'ThrCon8491123Entities' section of the application configuration file.
        /// </summary>
        public ThrCon8491123Entities() : base("name=ThrCon8491123Entities", "ThrCon8491123Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ThrCon8491123Entities object.
        /// </summary>
        public ThrCon8491123Entities(string connectionString) : base(connectionString, "ThrCon8491123Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ThrCon8491123Entities object.
        /// </summary>
        public ThrCon8491123Entities(EntityConnection connection) : base(connection, "ThrCon8491123Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GetPhysician_View> GetPhysician_View
        {
            get
            {
                if ((_GetPhysician_View == null))
                {
                    _GetPhysician_View = base.CreateObjectSet<GetPhysician_View>("GetPhysician_View");
                }
                return _GetPhysician_View;
            }
        }
        private ObjectSet<GetPhysician_View> _GetPhysician_View;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GetInsuranceList_View> GetInsuranceList_View
        {
            get
            {
                if ((_GetInsuranceList_View == null))
                {
                    _GetInsuranceList_View = base.CreateObjectSet<GetInsuranceList_View>("GetInsuranceList_View");
                }
                return _GetInsuranceList_View;
            }
        }
        private ObjectSet<GetInsuranceList_View> _GetInsuranceList_View;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<med_physdirectory_languages> med_physdirectory_languages
        {
            get
            {
                if ((_med_physdirectory_languages == null))
                {
                    _med_physdirectory_languages = base.CreateObjectSet<med_physdirectory_languages>("med_physdirectory_languages");
                }
                return _med_physdirectory_languages;
            }
        }
        private ObjectSet<med_physdirectory_languages> _med_physdirectory_languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<med_physdirectory_Specialty> med_physdirectory_Specialty
        {
            get
            {
                if ((_med_physdirectory_Specialty == null))
                {
                    _med_physdirectory_Specialty = base.CreateObjectSet<med_physdirectory_Specialty>("med_physdirectory_Specialty");
                }
                return _med_physdirectory_Specialty;
            }
        }
        private ObjectSet<med_physdirectory_Specialty> _med_physdirectory_Specialty;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HospitalAffiliationsList_View> HospitalAffiliationsList_View
        {
            get
            {
                if ((_HospitalAffiliationsList_View == null))
                {
                    _HospitalAffiliationsList_View = base.CreateObjectSet<HospitalAffiliationsList_View>("HospitalAffiliationsList_View");
                }
                return _HospitalAffiliationsList_View;
            }
        }
        private ObjectSet<HospitalAffiliationsList_View> _HospitalAffiliationsList_View;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Med_Physdirectory_Offices_View> Med_Physdirectory_Offices_View
        {
            get
            {
                if ((_Med_Physdirectory_Offices_View == null))
                {
                    _Med_Physdirectory_Offices_View = base.CreateObjectSet<Med_Physdirectory_Offices_View>("Med_Physdirectory_Offices_View");
                }
                return _Med_Physdirectory_Offices_View;
            }
        }
        private ObjectSet<Med_Physdirectory_Offices_View> _Med_Physdirectory_Offices_View;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GetPhysician_View EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGetPhysician_View(GetPhysician_View getPhysician_View)
        {
            base.AddObject("GetPhysician_View", getPhysician_View);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GetInsuranceList_View EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGetInsuranceList_View(GetInsuranceList_View getInsuranceList_View)
        {
            base.AddObject("GetInsuranceList_View", getInsuranceList_View);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the med_physdirectory_languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomed_physdirectory_languages(med_physdirectory_languages med_physdirectory_languages)
        {
            base.AddObject("med_physdirectory_languages", med_physdirectory_languages);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the med_physdirectory_Specialty EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomed_physdirectory_Specialty(med_physdirectory_Specialty med_physdirectory_Specialty)
        {
            base.AddObject("med_physdirectory_Specialty", med_physdirectory_Specialty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HospitalAffiliationsList_View EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHospitalAffiliationsList_View(HospitalAffiliationsList_View hospitalAffiliationsList_View)
        {
            base.AddObject("HospitalAffiliationsList_View", hospitalAffiliationsList_View);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Med_Physdirectory_Offices_View EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMed_Physdirectory_Offices_View(Med_Physdirectory_Offices_View med_Physdirectory_Offices_View)
        {
            base.AddObject("Med_Physdirectory_Offices_View", med_Physdirectory_Offices_View);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetInsuranceList_View> getinsuranceList()
        {
            return base.ExecuteFunction<GetInsuranceList_View>("getinsuranceList");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<GetInsuranceList_View> getinsuranceList(MergeOption mergeOption)
        {
            return base.ExecuteFunction<GetInsuranceList_View>("getinsuranceList", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<med_physdirectory_languages> getSearchListLanguages()
        {
            return base.ExecuteFunction<med_physdirectory_languages>("getSearchListLanguages");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<med_physdirectory_languages> getSearchListLanguages(MergeOption mergeOption)
        {
            return base.ExecuteFunction<med_physdirectory_languages>("getSearchListLanguages", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<med_physdirectory_Specialty> getSearchListSpecialties()
        {
            return base.ExecuteFunction<med_physdirectory_Specialty>("getSearchListSpecialties");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<med_physdirectory_Specialty> getSearchListSpecialties(MergeOption mergeOption)
        {
            return base.ExecuteFunction<med_physdirectory_Specialty>("getSearchListSpecialties", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<HospitalAffiliationsList_View> getSearchListHospitalAffiliations()
        {
            return base.ExecuteFunction<HospitalAffiliationsList_View>("getSearchListHospitalAffiliations");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<HospitalAffiliationsList_View> getSearchListHospitalAffiliations(MergeOption mergeOption)
        {
            return base.ExecuteFunction<HospitalAffiliationsList_View>("getSearchListHospitalAffiliations", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="lname">No Metadata Documentation available.</param>
        /// <param name="fname">No Metadata Documentation available.</param>
        /// <param name="degree">No Metadata Documentation available.</param>
        /// <param name="gender">No Metadata Documentation available.</param>
        /// <param name="agemin">No Metadata Documentation available.</param>
        /// <param name="agemax">No Metadata Documentation available.</param>
        /// <param name="lang">No Metadata Documentation available.</param>
        /// <param name="spec">No Metadata Documentation available.</param>
        /// <param name="sameday">No Metadata Documentation available.</param>
        /// <param name="apptavail">No Metadata Documentation available.</param>
        /// <param name="hospaffil">No Metadata Documentation available.</param>
        /// <param name="insur">No Metadata Documentation available.</param>
        /// <param name="zip">No Metadata Documentation available.</param>
        /// <param name="latitude">No Metadata Documentation available.</param>
        /// <param name="longitude">No Metadata Documentation available.</param>
        /// <param name="distance">No Metadata Documentation available.</param>
        /// <param name="startFrom">No Metadata Documentation available.</param>
        /// <param name="numberOfRecords">No Metadata Documentation available.</param>
        public ObjectResult<GetPhysician_View> getPhysicianListwithPaging(global::System.String lname, global::System.String fname, global::System.String degree, global::System.String gender, Nullable<global::System.Int32> agemin, Nullable<global::System.Int32> agemax, global::System.String lang, global::System.String spec, global::System.String sameday, Nullable<global::System.Int32> apptavail, global::System.String hospaffil, Nullable<global::System.Int32> insur, global::System.String zip, Nullable<global::System.Single> latitude, Nullable<global::System.Single> longitude, Nullable<global::System.Int32> distance, Nullable<global::System.Int32> startFrom, Nullable<global::System.Int32> numberOfRecords)
        {
            ObjectParameter lnameParameter;
            if (lname != null)
            {
                lnameParameter = new ObjectParameter("lname", lname);
            }
            else
            {
                lnameParameter = new ObjectParameter("lname", typeof(global::System.String));
            }
    
            ObjectParameter fnameParameter;
            if (fname != null)
            {
                fnameParameter = new ObjectParameter("fname", fname);
            }
            else
            {
                fnameParameter = new ObjectParameter("fname", typeof(global::System.String));
            }
    
            ObjectParameter degreeParameter;
            if (degree != null)
            {
                degreeParameter = new ObjectParameter("degree", degree);
            }
            else
            {
                degreeParameter = new ObjectParameter("degree", typeof(global::System.String));
            }
    
            ObjectParameter genderParameter;
            if (gender != null)
            {
                genderParameter = new ObjectParameter("gender", gender);
            }
            else
            {
                genderParameter = new ObjectParameter("gender", typeof(global::System.String));
            }
    
            ObjectParameter ageminParameter;
            if (agemin.HasValue)
            {
                ageminParameter = new ObjectParameter("agemin", agemin);
            }
            else
            {
                ageminParameter = new ObjectParameter("agemin", typeof(global::System.Int32));
            }
    
            ObjectParameter agemaxParameter;
            if (agemax.HasValue)
            {
                agemaxParameter = new ObjectParameter("agemax", agemax);
            }
            else
            {
                agemaxParameter = new ObjectParameter("agemax", typeof(global::System.Int32));
            }
    
            ObjectParameter langParameter;
            if (lang != null)
            {
                langParameter = new ObjectParameter("lang", lang);
            }
            else
            {
                langParameter = new ObjectParameter("lang", typeof(global::System.String));
            }
    
            ObjectParameter specParameter;
            if (spec != null)
            {
                specParameter = new ObjectParameter("spec", spec);
            }
            else
            {
                specParameter = new ObjectParameter("spec", typeof(global::System.String));
            }
    
            ObjectParameter samedayParameter;
            if (sameday != null)
            {
                samedayParameter = new ObjectParameter("sameday", sameday);
            }
            else
            {
                samedayParameter = new ObjectParameter("sameday", typeof(global::System.String));
            }
    
            ObjectParameter apptavailParameter;
            if (apptavail.HasValue)
            {
                apptavailParameter = new ObjectParameter("apptavail", apptavail);
            }
            else
            {
                apptavailParameter = new ObjectParameter("apptavail", typeof(global::System.Int32));
            }
    
            ObjectParameter hospaffilParameter;
            if (hospaffil != null)
            {
                hospaffilParameter = new ObjectParameter("hospaffil", hospaffil);
            }
            else
            {
                hospaffilParameter = new ObjectParameter("hospaffil", typeof(global::System.String));
            }
    
            ObjectParameter insurParameter;
            if (insur.HasValue)
            {
                insurParameter = new ObjectParameter("insur", insur);
            }
            else
            {
                insurParameter = new ObjectParameter("insur", typeof(global::System.Int32));
            }
    
            ObjectParameter zipParameter;
            if (zip != null)
            {
                zipParameter = new ObjectParameter("zip", zip);
            }
            else
            {
                zipParameter = new ObjectParameter("zip", typeof(global::System.String));
            }
    
            ObjectParameter latitudeParameter;
            if (latitude.HasValue)
            {
                latitudeParameter = new ObjectParameter("latitude", latitude);
            }
            else
            {
                latitudeParameter = new ObjectParameter("latitude", typeof(global::System.Single));
            }
    
            ObjectParameter longitudeParameter;
            if (longitude.HasValue)
            {
                longitudeParameter = new ObjectParameter("longitude", longitude);
            }
            else
            {
                longitudeParameter = new ObjectParameter("longitude", typeof(global::System.Single));
            }
    
            ObjectParameter distanceParameter;
            if (distance.HasValue)
            {
                distanceParameter = new ObjectParameter("distance", distance);
            }
            else
            {
                distanceParameter = new ObjectParameter("distance", typeof(global::System.Int32));
            }
    
            ObjectParameter startFromParameter;
            if (startFrom.HasValue)
            {
                startFromParameter = new ObjectParameter("StartFrom", startFrom);
            }
            else
            {
                startFromParameter = new ObjectParameter("StartFrom", typeof(global::System.Int32));
            }
    
            ObjectParameter numberOfRecordsParameter;
            if (numberOfRecords.HasValue)
            {
                numberOfRecordsParameter = new ObjectParameter("NumberOfRecords", numberOfRecords);
            }
            else
            {
                numberOfRecordsParameter = new ObjectParameter("NumberOfRecords", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetPhysician_View>("getPhysicianListwithPaging", lnameParameter, fnameParameter, degreeParameter, genderParameter, ageminParameter, agemaxParameter, langParameter, specParameter, samedayParameter, apptavailParameter, hospaffilParameter, insurParameter, zipParameter, latitudeParameter, longitudeParameter, distanceParameter, startFromParameter, numberOfRecordsParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="lname">No Metadata Documentation available.</param>
        /// <param name="fname">No Metadata Documentation available.</param>
        /// <param name="degree">No Metadata Documentation available.</param>
        /// <param name="gender">No Metadata Documentation available.</param>
        /// <param name="agemin">No Metadata Documentation available.</param>
        /// <param name="agemax">No Metadata Documentation available.</param>
        /// <param name="lang">No Metadata Documentation available.</param>
        /// <param name="spec">No Metadata Documentation available.</param>
        /// <param name="sameday">No Metadata Documentation available.</param>
        /// <param name="apptavail">No Metadata Documentation available.</param>
        /// <param name="hospaffil">No Metadata Documentation available.</param>
        /// <param name="insur">No Metadata Documentation available.</param>
        /// <param name="zip">No Metadata Documentation available.</param>
        /// <param name="latitude">No Metadata Documentation available.</param>
        /// <param name="longitude">No Metadata Documentation available.</param>
        /// <param name="distance">No Metadata Documentation available.</param>
        /// <param name="startFrom">No Metadata Documentation available.</param>
        /// <param name="numberOfRecords">No Metadata Documentation available.</param>
        public ObjectResult<GetPhysician_View> getPhysicianListwithPaging(global::System.String lname, global::System.String fname, global::System.String degree, global::System.String gender, Nullable<global::System.Int32> agemin, Nullable<global::System.Int32> agemax, global::System.String lang, global::System.String spec, global::System.String sameday, Nullable<global::System.Int32> apptavail, global::System.String hospaffil, Nullable<global::System.Int32> insur, global::System.String zip, Nullable<global::System.Single> latitude, Nullable<global::System.Single> longitude, Nullable<global::System.Int32> distance, Nullable<global::System.Int32> startFrom, Nullable<global::System.Int32> numberOfRecords, MergeOption mergeOption)
        {
            ObjectParameter lnameParameter;
            if (lname != null)
            {
                lnameParameter = new ObjectParameter("lname", lname);
            }
            else
            {
                lnameParameter = new ObjectParameter("lname", typeof(global::System.String));
            }
    
            ObjectParameter fnameParameter;
            if (fname != null)
            {
                fnameParameter = new ObjectParameter("fname", fname);
            }
            else
            {
                fnameParameter = new ObjectParameter("fname", typeof(global::System.String));
            }
    
            ObjectParameter degreeParameter;
            if (degree != null)
            {
                degreeParameter = new ObjectParameter("degree", degree);
            }
            else
            {
                degreeParameter = new ObjectParameter("degree", typeof(global::System.String));
            }
    
            ObjectParameter genderParameter;
            if (gender != null)
            {
                genderParameter = new ObjectParameter("gender", gender);
            }
            else
            {
                genderParameter = new ObjectParameter("gender", typeof(global::System.String));
            }
    
            ObjectParameter ageminParameter;
            if (agemin.HasValue)
            {
                ageminParameter = new ObjectParameter("agemin", agemin);
            }
            else
            {
                ageminParameter = new ObjectParameter("agemin", typeof(global::System.Int32));
            }
    
            ObjectParameter agemaxParameter;
            if (agemax.HasValue)
            {
                agemaxParameter = new ObjectParameter("agemax", agemax);
            }
            else
            {
                agemaxParameter = new ObjectParameter("agemax", typeof(global::System.Int32));
            }
    
            ObjectParameter langParameter;
            if (lang != null)
            {
                langParameter = new ObjectParameter("lang", lang);
            }
            else
            {
                langParameter = new ObjectParameter("lang", typeof(global::System.String));
            }
    
            ObjectParameter specParameter;
            if (spec != null)
            {
                specParameter = new ObjectParameter("spec", spec);
            }
            else
            {
                specParameter = new ObjectParameter("spec", typeof(global::System.String));
            }
    
            ObjectParameter samedayParameter;
            if (sameday != null)
            {
                samedayParameter = new ObjectParameter("sameday", sameday);
            }
            else
            {
                samedayParameter = new ObjectParameter("sameday", typeof(global::System.String));
            }
    
            ObjectParameter apptavailParameter;
            if (apptavail.HasValue)
            {
                apptavailParameter = new ObjectParameter("apptavail", apptavail);
            }
            else
            {
                apptavailParameter = new ObjectParameter("apptavail", typeof(global::System.Int32));
            }
    
            ObjectParameter hospaffilParameter;
            if (hospaffil != null)
            {
                hospaffilParameter = new ObjectParameter("hospaffil", hospaffil);
            }
            else
            {
                hospaffilParameter = new ObjectParameter("hospaffil", typeof(global::System.String));
            }
    
            ObjectParameter insurParameter;
            if (insur.HasValue)
            {
                insurParameter = new ObjectParameter("insur", insur);
            }
            else
            {
                insurParameter = new ObjectParameter("insur", typeof(global::System.Int32));
            }
    
            ObjectParameter zipParameter;
            if (zip != null)
            {
                zipParameter = new ObjectParameter("zip", zip);
            }
            else
            {
                zipParameter = new ObjectParameter("zip", typeof(global::System.String));
            }
    
            ObjectParameter latitudeParameter;
            if (latitude.HasValue)
            {
                latitudeParameter = new ObjectParameter("latitude", latitude);
            }
            else
            {
                latitudeParameter = new ObjectParameter("latitude", typeof(global::System.Single));
            }
    
            ObjectParameter longitudeParameter;
            if (longitude.HasValue)
            {
                longitudeParameter = new ObjectParameter("longitude", longitude);
            }
            else
            {
                longitudeParameter = new ObjectParameter("longitude", typeof(global::System.Single));
            }
    
            ObjectParameter distanceParameter;
            if (distance.HasValue)
            {
                distanceParameter = new ObjectParameter("distance", distance);
            }
            else
            {
                distanceParameter = new ObjectParameter("distance", typeof(global::System.Int32));
            }
    
            ObjectParameter startFromParameter;
            if (startFrom.HasValue)
            {
                startFromParameter = new ObjectParameter("StartFrom", startFrom);
            }
            else
            {
                startFromParameter = new ObjectParameter("StartFrom", typeof(global::System.Int32));
            }
    
            ObjectParameter numberOfRecordsParameter;
            if (numberOfRecords.HasValue)
            {
                numberOfRecordsParameter = new ObjectParameter("NumberOfRecords", numberOfRecords);
            }
            else
            {
                numberOfRecordsParameter = new ObjectParameter("NumberOfRecords", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetPhysician_View>("getPhysicianListwithPaging", mergeOption, lnameParameter, fnameParameter, degreeParameter, genderParameter, ageminParameter, agemaxParameter, langParameter, specParameter, samedayParameter, apptavailParameter, hospaffilParameter, insurParameter, zipParameter, latitudeParameter, longitudeParameter, distanceParameter, startFromParameter, numberOfRecordsParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ids">No Metadata Documentation available.</param>
        public ObjectResult<Med_Physdirectory_Offices_View> getPhysicianOffices(global::System.String ids)
        {
            ObjectParameter idsParameter;
            if (ids != null)
            {
                idsParameter = new ObjectParameter("ids", ids);
            }
            else
            {
                idsParameter = new ObjectParameter("ids", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Med_Physdirectory_Offices_View>("getPhysicianOffices", idsParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="ids">No Metadata Documentation available.</param>
        public ObjectResult<Med_Physdirectory_Offices_View> getPhysicianOffices(global::System.String ids, MergeOption mergeOption)
        {
            ObjectParameter idsParameter;
            if (ids != null)
            {
                idsParameter = new ObjectParameter("ids", ids);
            }
            else
            {
                idsParameter = new ObjectParameter("ids", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Med_Physdirectory_Offices_View>("getPhysicianOffices", mergeOption, idsParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="GetInsuranceList_View")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GetInsuranceList_View : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetInsuranceList_View object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static GetInsuranceList_View CreateGetInsuranceList_View(global::System.Int32 id)
        {
            GetInsuranceList_View getInsuranceList_View = new GetInsuranceList_View();
            getInsuranceList_View.id = id;
            return getInsuranceList_View;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="GetPhysician_View")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GetPhysician_View : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetPhysician_View object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="facility">Initial value of the facility property.</param>
        /// <param name="medical_school">Initial value of the medical_school property.</param>
        /// <param name="internship">Initial value of the internship property.</param>
        /// <param name="residency">Initial value of the residency property.</param>
        /// <param name="fellowship">Initial value of the fellowship property.</param>
        /// <param name="primaryhospital">Initial value of the primaryhospital property.</param>
        /// <param name="secondaryhospital">Initial value of the secondaryhospital property.</param>
        /// <param name="apptavailability">Initial value of the apptavailability property.</param>
        /// <param name="zip_latitude">Initial value of the zip_latitude property.</param>
        /// <param name="zip_longitude">Initial value of the zip_longitude property.</param>
        /// <param name="addr_latitude">Initial value of the addr_latitude property.</param>
        /// <param name="addr_longitude">Initial value of the addr_longitude property.</param>
        public static GetPhysician_View CreateGetPhysician_View(global::System.Int32 id, global::System.String facility, global::System.String medical_school, global::System.String internship, global::System.String residency, global::System.String fellowship, global::System.String primaryhospital, global::System.String secondaryhospital, global::System.Int32 apptavailability, global::System.Single zip_latitude, global::System.Single zip_longitude, global::System.Single addr_latitude, global::System.Single addr_longitude)
        {
            GetPhysician_View getPhysician_View = new GetPhysician_View();
            getPhysician_View.id = id;
            getPhysician_View.facility = facility;
            getPhysician_View.medical_school = medical_school;
            getPhysician_View.internship = internship;
            getPhysician_View.residency = residency;
            getPhysician_View.fellowship = fellowship;
            getPhysician_View.primaryhospital = primaryhospital;
            getPhysician_View.secondaryhospital = secondaryhospital;
            getPhysician_View.apptavailability = apptavailability;
            getPhysician_View.zip_latitude = zip_latitude;
            getPhysician_View.zip_longitude = zip_longitude;
            getPhysician_View.addr_latitude = addr_latitude;
            getPhysician_View.addr_longitude = addr_longitude;
            return getPhysician_View;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String poid
        {
            get
            {
                return _poid;
            }
            set
            {
                OnpoidChanging(value);
                ReportPropertyChanging("poid");
                _poid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("poid");
                OnpoidChanged();
            }
        }
        private global::System.String _poid;
        partial void OnpoidChanging(global::System.String value);
        partial void OnpoidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String middleinitial
        {
            get
            {
                return _middleinitial;
            }
            set
            {
                OnmiddleinitialChanging(value);
                ReportPropertyChanging("middleinitial");
                _middleinitial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("middleinitial");
                OnmiddleinitialChanged();
            }
        }
        private global::System.String _middleinitial;
        partial void OnmiddleinitialChanging(global::System.String value);
        partial void OnmiddleinitialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Degree
        {
            get
            {
                return _Degree;
            }
            set
            {
                OnDegreeChanging(value);
                ReportPropertyChanging("Degree");
                _Degree = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Degree");
                OnDegreeChanged();
            }
        }
        private global::System.String _Degree;
        partial void OnDegreeChanging(global::System.String value);
        partial void OnDegreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String street2
        {
            get
            {
                return _street2;
            }
            set
            {
                Onstreet2Changing(value);
                ReportPropertyChanging("street2");
                _street2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("street2");
                Onstreet2Changed();
            }
        }
        private global::System.String _street2;
        partial void Onstreet2Changing(global::System.String value);
        partial void Onstreet2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fax
        {
            get
            {
                return _fax;
            }
            set
            {
                OnfaxChanging(value);
                ReportPropertyChanging("fax");
                _fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fax");
                OnfaxChanged();
            }
        }
        private global::System.String _fax;
        partial void OnfaxChanging(global::System.String value);
        partial void OnfaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String facility
        {
            get
            {
                return _facility;
            }
            set
            {
                if (_facility != value)
                {
                    OnfacilityChanging(value);
                    ReportPropertyChanging("facility");
                    _facility = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("facility");
                    OnfacilityChanged();
                }
            }
        }
        private global::System.String _facility;
        partial void OnfacilityChanging(global::System.String value);
        partial void OnfacilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.String _Photo;
        partial void OnPhotoChanging(global::System.String value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String specialty1
        {
            get
            {
                return _specialty1;
            }
            set
            {
                Onspecialty1Changing(value);
                ReportPropertyChanging("specialty1");
                _specialty1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("specialty1");
                Onspecialty1Changed();
            }
        }
        private global::System.String _specialty1;
        partial void Onspecialty1Changing(global::System.String value);
        partial void Onspecialty1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String specialty2
        {
            get
            {
                return _specialty2;
            }
            set
            {
                Onspecialty2Changing(value);
                ReportPropertyChanging("specialty2");
                _specialty2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("specialty2");
                Onspecialty2Changed();
            }
        }
        private global::System.String _specialty2;
        partial void Onspecialty2Changing(global::System.String value);
        partial void Onspecialty2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String specialty3
        {
            get
            {
                return _specialty3;
            }
            set
            {
                Onspecialty3Changing(value);
                ReportPropertyChanging("specialty3");
                _specialty3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("specialty3");
                Onspecialty3Changed();
            }
        }
        private global::System.String _specialty3;
        partial void Onspecialty3Changing(global::System.String value);
        partial void Onspecialty3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String specialty4
        {
            get
            {
                return _specialty4;
            }
            set
            {
                Onspecialty4Changing(value);
                ReportPropertyChanging("specialty4");
                _specialty4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("specialty4");
                Onspecialty4Changed();
            }
        }
        private global::System.String _specialty4;
        partial void Onspecialty4Changing(global::System.String value);
        partial void Onspecialty4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String certification
        {
            get
            {
                return _certification;
            }
            set
            {
                OncertificationChanging(value);
                ReportPropertyChanging("certification");
                _certification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("certification");
                OncertificationChanged();
            }
        }
        private global::System.String _certification;
        partial void OncertificationChanging(global::System.String value);
        partial void OncertificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String medical_school
        {
            get
            {
                return _medical_school;
            }
            set
            {
                if (_medical_school != value)
                {
                    Onmedical_schoolChanging(value);
                    ReportPropertyChanging("medical_school");
                    _medical_school = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("medical_school");
                    Onmedical_schoolChanged();
                }
            }
        }
        private global::System.String _medical_school;
        partial void Onmedical_schoolChanging(global::System.String value);
        partial void Onmedical_schoolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String internship
        {
            get
            {
                return _internship;
            }
            set
            {
                if (_internship != value)
                {
                    OninternshipChanging(value);
                    ReportPropertyChanging("internship");
                    _internship = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("internship");
                    OninternshipChanged();
                }
            }
        }
        private global::System.String _internship;
        partial void OninternshipChanging(global::System.String value);
        partial void OninternshipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String residency
        {
            get
            {
                return _residency;
            }
            set
            {
                if (_residency != value)
                {
                    OnresidencyChanging(value);
                    ReportPropertyChanging("residency");
                    _residency = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("residency");
                    OnresidencyChanged();
                }
            }
        }
        private global::System.String _residency;
        partial void OnresidencyChanging(global::System.String value);
        partial void OnresidencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fellowship
        {
            get
            {
                return _fellowship;
            }
            set
            {
                if (_fellowship != value)
                {
                    OnfellowshipChanging(value);
                    ReportPropertyChanging("fellowship");
                    _fellowship = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("fellowship");
                    OnfellowshipChanged();
                }
            }
        }
        private global::System.String _fellowship;
        partial void OnfellowshipChanging(global::System.String value);
        partial void OnfellowshipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hospitalaffiliation
        {
            get
            {
                return _hospitalaffiliation;
            }
            set
            {
                OnhospitalaffiliationChanging(value);
                ReportPropertyChanging("hospitalaffiliation");
                _hospitalaffiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hospitalaffiliation");
                OnhospitalaffiliationChanged();
            }
        }
        private global::System.String _hospitalaffiliation;
        partial void OnhospitalaffiliationChanging(global::System.String value);
        partial void OnhospitalaffiliationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String primaryhospital
        {
            get
            {
                return _primaryhospital;
            }
            set
            {
                if (_primaryhospital != value)
                {
                    OnprimaryhospitalChanging(value);
                    ReportPropertyChanging("primaryhospital");
                    _primaryhospital = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("primaryhospital");
                    OnprimaryhospitalChanged();
                }
            }
        }
        private global::System.String _primaryhospital;
        partial void OnprimaryhospitalChanging(global::System.String value);
        partial void OnprimaryhospitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String secondaryhospital
        {
            get
            {
                return _secondaryhospital;
            }
            set
            {
                if (_secondaryhospital != value)
                {
                    OnsecondaryhospitalChanging(value);
                    ReportPropertyChanging("secondaryhospital");
                    _secondaryhospital = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("secondaryhospital");
                    OnsecondaryhospitalChanged();
                }
            }
        }
        private global::System.String _secondaryhospital;
        partial void OnsecondaryhospitalChanging(global::System.String value);
        partial void OnsecondaryhospitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String languages
        {
            get
            {
                return _languages;
            }
            set
            {
                OnlanguagesChanging(value);
                ReportPropertyChanging("languages");
                _languages = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("languages");
                OnlanguagesChanged();
            }
        }
        private global::System.String _languages;
        partial void OnlanguagesChanging(global::System.String value);
        partial void OnlanguagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String practicingsince
        {
            get
            {
                return _practicingsince;
            }
            set
            {
                OnpracticingsinceChanging(value);
                ReportPropertyChanging("practicingsince");
                _practicingsince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("practicingsince");
                OnpracticingsinceChanged();
            }
        }
        private global::System.String _practicingsince;
        partial void OnpracticingsinceChanging(global::System.String value);
        partial void OnpracticingsinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String practicetype
        {
            get
            {
                return _practicetype;
            }
            set
            {
                OnpracticetypeChanging(value);
                ReportPropertyChanging("practicetype");
                _practicetype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("practicetype");
                OnpracticetypeChanged();
            }
        }
        private global::System.String _practicetype;
        partial void OnpracticetypeChanging(global::System.String value);
        partial void OnpracticetypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptingnewpatients
        {
            get
            {
                return _acceptingnewpatients;
            }
            set
            {
                OnacceptingnewpatientsChanging(value);
                ReportPropertyChanging("acceptingnewpatients");
                _acceptingnewpatients = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptingnewpatients");
                OnacceptingnewpatientsChanged();
            }
        }
        private global::System.String _acceptingnewpatients;
        partial void OnacceptingnewpatientsChanging(global::System.String value);
        partial void OnacceptingnewpatientsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String samedayappt
        {
            get
            {
                return _samedayappt;
            }
            set
            {
                OnsamedayapptChanging(value);
                ReportPropertyChanging("samedayappt");
                _samedayappt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("samedayappt");
                OnsamedayapptChanged();
            }
        }
        private global::System.String _samedayappt;
        partial void OnsamedayapptChanging(global::System.String value);
        partial void OnsamedayapptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 apptavailability
        {
            get
            {
                return _apptavailability;
            }
            set
            {
                if (_apptavailability != value)
                {
                    OnapptavailabilityChanging(value);
                    ReportPropertyChanging("apptavailability");
                    _apptavailability = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("apptavailability");
                    OnapptavailabilityChanged();
                }
            }
        }
        private global::System.Int32 _apptavailability;
        partial void OnapptavailabilityChanging(global::System.Int32 value);
        partial void OnapptavailabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptingonlineappts
        {
            get
            {
                return _acceptingonlineappts;
            }
            set
            {
                OnacceptingonlineapptsChanging(value);
                ReportPropertyChanging("acceptingonlineappts");
                _acceptingonlineappts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptingonlineappts");
                OnacceptingonlineapptsChanged();
            }
        }
        private global::System.String _acceptingonlineappts;
        partial void OnacceptingonlineapptsChanging(global::System.String value);
        partial void OnacceptingonlineapptsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String websiteurl
        {
            get
            {
                return _websiteurl;
            }
            set
            {
                OnwebsiteurlChanging(value);
                ReportPropertyChanging("websiteurl");
                _websiteurl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("websiteurl");
                OnwebsiteurlChanged();
            }
        }
        private global::System.String _websiteurl;
        partial void OnwebsiteurlChanging(global::System.String value);
        partial void OnwebsiteurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String patient_portal
        {
            get
            {
                return _patient_portal;
            }
            set
            {
                Onpatient_portalChanging(value);
                ReportPropertyChanging("patient_portal");
                _patient_portal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("patient_portal");
                Onpatient_portalChanged();
            }
        }
        private global::System.String _patient_portal;
        partial void Onpatient_portalChanging(global::System.String value);
        partial void Onpatient_portalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> physician_group
        {
            get
            {
                return _physician_group;
            }
            set
            {
                Onphysician_groupChanging(value);
                ReportPropertyChanging("physician_group");
                _physician_group = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("physician_group");
                Onphysician_groupChanged();
            }
        }
        private Nullable<global::System.Boolean> _physician_group;
        partial void Onphysician_groupChanging(Nullable<global::System.Boolean> value);
        partial void Onphysician_groupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> m_date_create
        {
            get
            {
                return _m_date_create;
            }
            set
            {
                Onm_date_createChanging(value);
                ReportPropertyChanging("m_date_create");
                _m_date_create = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_date_create");
                Onm_date_createChanged();
            }
        }
        private Nullable<global::System.DateTime> _m_date_create;
        partial void Onm_date_createChanging(Nullable<global::System.DateTime> value);
        partial void Onm_date_createChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> m_date_mod
        {
            get
            {
                return _m_date_mod;
            }
            set
            {
                Onm_date_modChanging(value);
                ReportPropertyChanging("m_date_mod");
                _m_date_mod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("m_date_mod");
                Onm_date_modChanged();
            }
        }
        private Nullable<global::System.DateTime> _m_date_mod;
        partial void Onm_date_modChanging(Nullable<global::System.DateTime> value);
        partial void Onm_date_modChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single zip_latitude
        {
            get
            {
                return _zip_latitude;
            }
            set
            {
                if (_zip_latitude != value)
                {
                    Onzip_latitudeChanging(value);
                    ReportPropertyChanging("zip_latitude");
                    _zip_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("zip_latitude");
                    Onzip_latitudeChanged();
                }
            }
        }
        private global::System.Single _zip_latitude;
        partial void Onzip_latitudeChanging(global::System.Single value);
        partial void Onzip_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single zip_longitude
        {
            get
            {
                return _zip_longitude;
            }
            set
            {
                if (_zip_longitude != value)
                {
                    Onzip_longitudeChanging(value);
                    ReportPropertyChanging("zip_longitude");
                    _zip_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("zip_longitude");
                    Onzip_longitudeChanged();
                }
            }
        }
        private global::System.Single _zip_longitude;
        partial void Onzip_longitudeChanging(global::System.Single value);
        partial void Onzip_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single addr_latitude
        {
            get
            {
                return _addr_latitude;
            }
            set
            {
                if (_addr_latitude != value)
                {
                    Onaddr_latitudeChanging(value);
                    ReportPropertyChanging("addr_latitude");
                    _addr_latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("addr_latitude");
                    Onaddr_latitudeChanged();
                }
            }
        }
        private global::System.Single _addr_latitude;
        partial void Onaddr_latitudeChanging(global::System.Single value);
        partial void Onaddr_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single addr_longitude
        {
            get
            {
                return _addr_longitude;
            }
            set
            {
                if (_addr_longitude != value)
                {
                    Onaddr_longitudeChanging(value);
                    ReportPropertyChanging("addr_longitude");
                    _addr_longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("addr_longitude");
                    Onaddr_longitudeChanged();
                }
            }
        }
        private global::System.Single _addr_longitude;
        partial void Onaddr_longitudeChanging(global::System.Single value);
        partial void Onaddr_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> miles_from_here
        {
            get
            {
                return _miles_from_here;
            }
            set
            {
                Onmiles_from_hereChanging(value);
                ReportPropertyChanging("miles_from_here");
                _miles_from_here = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("miles_from_here");
                Onmiles_from_hereChanged();
            }
        }
        private Nullable<global::System.Decimal> _miles_from_here;
        partial void Onmiles_from_hereChanging(Nullable<global::System.Decimal> value);
        partial void Onmiles_from_hereChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RowNumber
        {
            get
            {
                return _RowNumber;
            }
            set
            {
                OnRowNumberChanging(value);
                ReportPropertyChanging("RowNumber");
                _RowNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowNumber");
                OnRowNumberChanged();
            }
        }
        private Nullable<global::System.Int64> _RowNumber;
        partial void OnRowNumberChanging(Nullable<global::System.Int64> value);
        partial void OnRowNumberChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="HospitalAffiliationsList_View")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HospitalAffiliationsList_View : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HospitalAffiliationsList_View object.
        /// </summary>
        /// <param name="description">Initial value of the description property.</param>
        public static HospitalAffiliationsList_View CreateHospitalAffiliationsList_View(global::System.String description)
        {
            HospitalAffiliationsList_View hospitalAffiliationsList_View = new HospitalAffiliationsList_View();
            hospitalAffiliationsList_View.description = description;
            return hospitalAffiliationsList_View;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                if (_description != value)
                {
                    OndescriptionChanging(value);
                    ReportPropertyChanging("description");
                    _description = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("description");
                    OndescriptionChanged();
                }
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="med_physdirectory_languages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class med_physdirectory_languages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new med_physdirectory_languages object.
        /// </summary>
        /// <param name="ref">Initial value of the ref property.</param>
        public static med_physdirectory_languages Createmed_physdirectory_languages(global::System.Int32 @ref)
        {
            med_physdirectory_languages med_physdirectory_languages = new med_physdirectory_languages();
            med_physdirectory_languages.@ref = @ref;
            return med_physdirectory_languages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @ref
        {
            get
            {
                return _ref;
            }
            set
            {
                if (_ref != value)
                {
                    OnrefChanging(value);
                    ReportPropertyChanging("ref");
                    _ref = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ref");
                    OnrefChanged();
                }
            }
        }
        private global::System.Int32 _ref;
        partial void OnrefChanging(global::System.Int32 value);
        partial void OnrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String keyvalue
        {
            get
            {
                return _keyvalue;
            }
            set
            {
                OnkeyvalueChanging(value);
                ReportPropertyChanging("keyvalue");
                _keyvalue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("keyvalue");
                OnkeyvalueChanged();
            }
        }
        private global::System.String _keyvalue;
        partial void OnkeyvalueChanging(global::System.String value);
        partial void OnkeyvalueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="Med_Physdirectory_Offices_View")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Med_Physdirectory_Offices_View : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Med_Physdirectory_Offices_View object.
        /// </summary>
        /// <param name="ref">Initial value of the ref property.</param>
        /// <param name="zip">Initial value of the zip property.</param>
        public static Med_Physdirectory_Offices_View CreateMed_Physdirectory_Offices_View(global::System.Int32 @ref, global::System.String zip)
        {
            Med_Physdirectory_Offices_View med_Physdirectory_Offices_View = new Med_Physdirectory_Offices_View();
            med_Physdirectory_Offices_View.@ref = @ref;
            med_Physdirectory_Offices_View.zip = zip;
            return med_Physdirectory_Offices_View;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @ref
        {
            get
            {
                return _ref;
            }
            set
            {
                if (_ref != value)
                {
                    OnrefChanging(value);
                    ReportPropertyChanging("ref");
                    _ref = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ref");
                    OnrefChanged();
                }
            }
        }
        private global::System.Int32 _ref;
        partial void OnrefChanging(global::System.Int32 value);
        partial void OnrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userrecordref
        {
            get
            {
                return _userrecordref;
            }
            set
            {
                OnuserrecordrefChanging(value);
                ReportPropertyChanging("userrecordref");
                _userrecordref = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userrecordref");
                OnuserrecordrefChanged();
            }
        }
        private Nullable<global::System.Int32> _userrecordref;
        partial void OnuserrecordrefChanging(Nullable<global::System.Int32> value);
        partial void OnuserrecordrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String primaryoffice
        {
            get
            {
                return _primaryoffice;
            }
            set
            {
                OnprimaryofficeChanging(value);
                ReportPropertyChanging("primaryoffice");
                _primaryoffice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("primaryoffice");
                OnprimaryofficeChanged();
            }
        }
        private global::System.String _primaryoffice;
        partial void OnprimaryofficeChanging(global::System.String value);
        partial void OnprimaryofficeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String locationname
        {
            get
            {
                return _locationname;
            }
            set
            {
                OnlocationnameChanging(value);
                ReportPropertyChanging("locationname");
                _locationname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("locationname");
                OnlocationnameChanged();
            }
        }
        private global::System.String _locationname;
        partial void OnlocationnameChanging(global::System.String value);
        partial void OnlocationnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address1
        {
            get
            {
                return _address1;
            }
            set
            {
                Onaddress1Changing(value);
                ReportPropertyChanging("address1");
                _address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address1");
                Onaddress1Changed();
            }
        }
        private global::System.String _address1;
        partial void Onaddress1Changing(global::System.String value);
        partial void Onaddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address2
        {
            get
            {
                return _address2;
            }
            set
            {
                Onaddress2Changing(value);
                ReportPropertyChanging("address2");
                _address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address2");
                Onaddress2Changed();
            }
        }
        private global::System.String _address2;
        partial void Onaddress2Changing(global::System.String value);
        partial void Onaddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                if (_zip != value)
                {
                    OnzipChanging(value);
                    ReportPropertyChanging("zip");
                    _zip = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("zip");
                    OnzipChanged();
                }
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fax
        {
            get
            {
                return _fax;
            }
            set
            {
                OnfaxChanging(value);
                ReportPropertyChanging("fax");
                _fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fax");
                OnfaxChanged();
            }
        }
        private global::System.String _fax;
        partial void OnfaxChanging(global::System.String value);
        partial void OnfaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hours
        {
            get
            {
                return _hours;
            }
            set
            {
                OnhoursChanging(value);
                ReportPropertyChanging("hours");
                _hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hours");
                OnhoursChanged();
            }
        }
        private global::System.String _hours;
        partial void OnhoursChanging(global::System.String value);
        partial void OnhoursChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThrCon8491123Model", Name="med_physdirectory_Specialty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class med_physdirectory_Specialty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new med_physdirectory_Specialty object.
        /// </summary>
        /// <param name="ref">Initial value of the ref property.</param>
        public static med_physdirectory_Specialty Createmed_physdirectory_Specialty(global::System.Int32 @ref)
        {
            med_physdirectory_Specialty med_physdirectory_Specialty = new med_physdirectory_Specialty();
            med_physdirectory_Specialty.@ref = @ref;
            return med_physdirectory_Specialty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @ref
        {
            get
            {
                return _ref;
            }
            set
            {
                if (_ref != value)
                {
                    OnrefChanging(value);
                    ReportPropertyChanging("ref");
                    _ref = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ref");
                    OnrefChanged();
                }
            }
        }
        private global::System.Int32 _ref;
        partial void OnrefChanging(global::System.Int32 value);
        partial void OnrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String keyvalue
        {
            get
            {
                return _keyvalue;
            }
            set
            {
                OnkeyvalueChanging(value);
                ReportPropertyChanging("keyvalue");
                _keyvalue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("keyvalue");
                OnkeyvalueChanged();
            }
        }
        private global::System.String _keyvalue;
        partial void OnkeyvalueChanging(global::System.String value);
        partial void OnkeyvalueChanged();

        #endregion
    
    }

    #endregion
    
}
